### ISSUE TITLE
News ticker

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [themebeez/royale-news#14]
* Newsticker item overlaps in mobile view

**Comment by jhoonb** [comment]
And desktop too

**Comment by jhoonb** [comment]
append on **ticker-news** [_style.scss](https://github.com/themebeez/royale-news/blob/2708d6115bae1178906bb4bba49c220725a8c09f/assets/src/scss/custom/_style.scss#L154) white-space, overflow, text-overflow:
```css

.ticker-news {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
